### PR TITLE
fix: button background contrast

### PR DESCRIPTION
**Pull request by icarodredd**
## Description of the pull request

i changed the background color to via-900

## Changes made

- class="bg-gradient-to-b from-green-800 **via-green-900** to-green-950"

## Checklist

- [x] I have written tests
- [x] My code does not produce new errors
- [x] I gave myself a code review before asking others.

### CODE REVIEW

**Comment by GuiBibeau** [comment]
Thanks a lot for this! Please fill out the PR description. Reviewing now

**Review by GuiBibeau — APPROVED** [review]

**Comment by icarodredd** [comment]
closed #69

**Comment by cxalem** [comment]
I would say it's better to change the button color on mobile than changing the background color!

This is because the background pattern looks incomplete if we do this.

Another way to solve this is to change the background color only on mobile.

**Comment by GuiBibeau** [comment]
@cxalem or @tobySolutions can one of you give this a second review. I'm a bit removed from the UI currently

**Comment by icarodredd** [comment]
> I would say it's better to change the button color on mobile than to change the background color!
> 
> This is because the background pattern looks incomplete if we do this.
> 
> Another way to solve this is to change the background color only on mobile.

Yaya, but i don't see a big difference changing this. Well i left the decision for the owner and others contributors

**Comment by tobySolutions** [comment]
> > I would say it's better to change the button color on mobile than to change the background color!
> > This is because the background pattern looks incomplete if we do this.
> > Another way to solve this is to change the background color only on mobile.
> 
> Yaya, but i don't see a big difference changing this. Well i left the decision for the owner and others contributors

I agree with @cxalem's  suggestion on this. That the preferred solution, right now.

**Comment by GuiBibeau** [comment]
Agree with @cxalem and @tobySolutions on this

**Pull request closed without merging**
